config/routes.rb
Rails.application.routes.draw do
  root 'notes#index'
  resources :notes
  post '/notes/new' => 'notes#create'
  post '/notes/:id/edit' => 'notes#update'
  get '/signup' => 'users#new'
  resources :users
  get '/signin' => 'sessions#new'
  post '/signin' => 'sessions#create'

end

app/models/note.rb
class Note < ActiveRecord::Base
  has_and_belongs_to_many :tag
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_and_belongs_to_many :note
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
    def create
        @note = Note.new(note_params)
        @note.save
        redirect_to action: "index"
    end
    
    def index
        @notes = Note.order('notes.created_at DESC').all
    end

    def show
        @note = Note.find(params[:id])
    end

    def new
        @note = Note.new
    end

    def edit
        @note = Note.find(params[:id])
    end

    def update
        @note = Note.find(params[:id])
        if @note.update_attributes(note_params)
            redirect_to action: "index"
        else
            render 'edit'
        end
    end

    def destroy
        @note = Note.find(params[:id])
        @note.destroy
        redirect_to action: "index"
    end

    private
    def note_params
        params.require(:note).permit(:title, :text, :created_at)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by_email(params[:session][:email])
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      redirect_to '/'
    else
      flash.now[:danger] = 'Invalid login information'
      render 'new'
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to '/'
    else
      redirect_to '/signup'
    end
  end

  private
  def user_params
    params.require(:user).permit(:email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title)
    base_title = "Rote"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">

</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Rote", '#', id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Sign in", signin_path %></li>
        <li><%= link_to "About", '#' %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag 'application', media: 'all',
                          'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
  <![endif]-->
</head>
    <body>
        <%= render 'layouts/header' %>
        <div class="container">
          <% flash.each do |key, value| %>
              <%= content_tag :div, value, class: "alert alert-#{key}" %>
          <% end %>
          <%= yield %>
        </div>

        <%= render 'layouts/footer' %>
    </body>
</html>

app/views/notes/_fields.html.erb
<p>
  <%= f.label :title %><br>
  <%= f.text_field :title %>
</p>

<p>
  <%= f.label :text %><br>
  <%= f.text_area :text %>
</p>

<p>
  <%= f.submit %>
</p>

app/views/notes/edit.html.erb
<h2>Edit note</h2>
<%= form_for :note do |f| %>
    <%= render 'fields', f: f %>
<% end %>

app/views/notes/index.html.erb
<h1>Your notes:</h1>

<%= link_to image_tag('add.png'), new_note_path %>

<% @notes.each do |note| %>
  <div class="note">
    <h2><%= note.title %></h2>
    <p class="date"><%= note.created_at.strftime("%d %b %Y") %></p>
    <p><%= note.text %></p>
    <%= link_to image_tag('edit.png'), edit_note_path(id: note.id) %>
    <%= link_to image_tag('delete.png'), note_path(id: note.id), method: :delete,
      data: { confirm: "Are you sure?" } %>
  </div>
<% end %>

app/views/notes/new.html.erb
<%= form_for :note do |f| %>
    <fieldset>
      <legend>Add note</legend>
      <%= render 'fields', f: f %>
    </fieldset>
<% end %>

app/views/notes/show.html.erb
<h2>
    <strong><%= @note.title %></strong>
</h2>
<p>
    <%= note.text %>
</p>
<p>
    created at: <%= note.created_at %>
</p>

app/views/users/new.html.erb
<h2>Sign up</h2>

<%= form_for(@user) do |f| %>
    <%= f.email_field :email, :placeholder => "Email" %>
    <%= f.password_field :password, :placeholder => "Password" %>
    <%= f.submit "Create an account", class: "btn-submit" %>
<% end %>